; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = lpmsp430g2553

[env:lpmsp430g2553]
platform = timsp430
board = lpmsp430g2553
framework = arduino
monitor_speed = 115200
check_tool = clangtidy
build_flags = -Os -g -std=c++0x -Wl,-Map=${BUILD_DIR}/output.map,--cref
extra_scripts = post:tools/platformio_size_breakdown.py
debug_tool = custom
upload_command = /opt/homebrew/bin/mspdebug rf2500 "prog $SOURCE"
debug_server = 
    /opt/homebrew/bin/mspdebug 
    rf2500

[env:debug-full]
extends = env:lpmsp430g2553
build_type = debug
debug_build_flags = -Os -g3 -ggdb -gdwarf-2
extra_scripts =
    pre:tools/platformio_debug_optimization.py
    post:tools/platformio_size_breakdown.py

; symlink the local libs in the lib folder:
; cd to folder of this platformio.ini
; cd lib
; ln -s path/to/lettuce-sim/library/shelf/byte_stream byte_stream
; ln -s path/to/lettuce-sim/library/shelf/tui tui
